name = "aegirintel"
main = "worker.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"

# KV namespace for shared data
[[kv_namespaces]]
binding = "AEGIR_KV"
id = "96ca200638984c25b50a733435c86602"
